package cz.muni.fi.pb138.videokartoteka.gui;

import cz.muni.fi.pb138.videokartoteka.gui.components.MyTableCellRenderer;
import com.google.api.services.drive.model.File;
import com.google.api.services.drive.model.ParentReference;
import cz.muni.fi.pb138.videokartoteka.dommanager.DomManagerImpl;
import cz.muni.fi.pb138.videokartoteka.dommanager.MediaType;
import cz.muni.fi.pb138.videokartoteka.google.GoogleConnection;
import cz.muni.fi.pb138.videokartoteka.google.GoogleDriveService;
import cz.muni.fi.pb138.videokartoteka.gui.components.OdfTableModel;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Michal, Matus
 */
public class MainView extends javax.swing.JFrame {

    private GoogleConnection gc;
    private GoogleDriveService service;
    private DomManagerImpl manager;
    private File actualFile = new File();
    private boolean saved = true;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

        // Listen for changes in the text
        searchTF.getDocument().addDocumentListener(new DocumentListener() {
            // text was changed
            public void changedUpdate(DocumentEvent e) {
                searchText();
            }

            // text was deleted
            public void removeUpdate(DocumentEvent e) {
                searchText();
            }

            // text was inserted
            public void insertUpdate(DocumentEvent e) {
                searchText();
            }
        });
    }

    public void searchText() {
        if (!searchTF.getText().equals("")) {
            List idNumbers = manager.searchRecord(searchTF.getText(),
                    categoriesList.getSelectedValue().toString());
            MyTableCellRenderer renderer = new MyTableCellRenderer();
            renderer.setRows(idNumbers);
            recordsTable.setDefaultRenderer(Object.class, renderer);

            if (idNumbers.size() == 1) {
                searchLabel.setText("1 result found.");
            } else {
                searchLabel.setText(idNumbers.size() + " results found.");
            }

        } else {
            searchLabel.setText("");
            recordsTable.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        }

        OdfTableModel model = (OdfTableModel) recordsTable.getModel();
        model.fireUpdateAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectedPanel = new javax.swing.JPanel();
        disconnectButton = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        statusLabel = new javax.swing.JLabel();
        quickMenuBar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        connectionStateLabel = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        disconnectedPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        categoriesList = new javax.swing.JList();
        deleteCategoryButton = new javax.swing.JButton();
        addCategoryButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        deleteRecordButton = new javax.swing.JButton();
        editRecordButton = new javax.swing.JButton();
        addRecordButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        connectMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        openFileMenuItem = new javax.swing.JMenuItem();
        saveFileMenuItem = new javax.swing.JMenuItem();
        saveFileAsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        disconnectMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        connectedPanel.setBackground(new java.awt.Color(255, 255, 255));
        connectedPanel.setLayout(new java.awt.BorderLayout());

        disconnectButton.setText("Disconnect");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });
        connectedPanel.add(disconnectButton, java.awt.BorderLayout.CENTER);

        openFileButton.setText("Open");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });
        connectedPanel.add(openFileButton, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VideoKartoteka");
        setAutoRequestFocus(false);

        statusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusLabel.setName(""); // NOI18N

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(statusBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusLabel))
        );

        quickMenuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout quickMenuBarLayout = new javax.swing.GroupLayout(quickMenuBar);
        quickMenuBar.setLayout(quickMenuBarLayout);
        quickMenuBarLayout.setHorizontalGroup(
            quickMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        quickMenuBarLayout.setVerticalGroup(
            quickMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getImage("Google_Logo.png")));
        jPanel1.add(jLabel1);

        connectionStateLabel.setForeground(java.awt.Color.RED);
        connectionStateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        connectionStateLabel.setText("<html><b>Not connected</b></html>");
        jPanel1.add(connectionStateLabel);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton);

        disconnectedPanel.setBackground(new java.awt.Color(255, 255, 255));
        disconnectedPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                disconnectedPanelComponentHidden(evt);
            }
        });
        disconnectedPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("to your Google account");
        disconnectedPanel.add(jLabel3, new java.awt.GridBagConstraints());

        jPanel1.add(disconnectedPanel);

        jLabel2.setText("Categories");

        categoriesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        categoriesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoriesListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(categoriesList);

        deleteCategoryButton.setText("Delete");
        deleteCategoryButton.setEnabled(false);
        deleteCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryButtonActionPerformed(evt);
            }
        });

        addCategoryButton.setText("Add");
        addCategoryButton.setEnabled(false);
        addCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addCategoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCategoryButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategoryButton)
                    .addComponent(deleteCategoryButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        recordsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        recordsTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                recordsTableValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(recordsTable);

        deleteRecordButton.setText("Delete");
        deleteRecordButton.setEnabled(false);
        deleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButtonActionPerformed(evt);
            }
        });

        editRecordButton.setText("Edit");
        editRecordButton.setEnabled(false);
        editRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRecordButtonActionPerformed(evt);
            }
        });

        addRecordButton.setText("Add");
        addRecordButton.setEnabled(false);
        addRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordButtonActionPerformed(evt);
            }
        });

        searchLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(addRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteRecordButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRecordButton)
                    .addComponent(editRecordButton)
                    .addComponent(addRecordButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        searchLabel.getAccessibleContext().setAccessibleName("resultsLabel");

        jScrollPane2.setViewportView(jPanel3);

        jLabel4.setText("Search:");

        searchTF.setEnabled(false);
        searchTF.setName(""); // NOI18N

        jMenu1.setText("File");

        connectMenuItem.setText("Connect to GoogleDrive");
        connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jMenu1.add(connectMenuItem);
        jMenu1.add(jSeparator1);

        openFileMenuItem.setText("Open file");
        openFileMenuItem.setEnabled(false);
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });
        jMenu1.add(openFileMenuItem);

        saveFileMenuItem.setText("Save file");
        saveFileMenuItem.setEnabled(false);
        saveFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });
        jMenu1.add(saveFileMenuItem);

        saveFileAsMenuItem.setText("Save file as...");
        saveFileAsMenuItem.setEnabled(false);
        saveFileAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsFileButtonActionPerformed(evt);
            }
        });
        jMenu1.add(saveFileAsMenuItem);
        jMenu1.add(jSeparator2);

        disconnectMenuItem.setText("Disconnect");
        disconnectMenuItem.setEnabled(false);
        disconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });
        jMenu1.add(disconnectMenuItem);

        exitMenuItem.setText("End");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(quickMenuBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(quickMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if (gc == null) {
            gc = new GoogleConnection();
        }
        GoogleConnectionDialog gcd = new GoogleConnectionDialog(this, true);
        gcd.setLocationRelativeTo(this);
        gcd.setConnectionUrl(gc.getAuthorizationUrl());

        if (Desktop.isDesktopSupported()) {
            try {
                Desktop desktop = Desktop.getDesktop();
                
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI(gc.getAuthorizationUrl()));
                }
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        int result = gcd.showDialog();

        if (result == GoogleConnectionDialog.RESULT_OK) {
            SwingWorker task = new ConnectToGoogleDriveTask(gc, gcd.getCode());
            task.addPropertyChangeListener(
                    new PropertyChangeListener() {
                        public void propertyChange(PropertyChangeEvent evt) {
                            if ("state".equals(evt.getPropertyName())) {
                                Object value = evt.getNewValue();
                                if (value.equals(SwingWorker.StateValue.STARTED)) {
                                    statusLabel.setText("Connecting to authorisation service Google");
                                    progressBar.setValue(20);
                                }
                                if (value.equals(SwingWorker.StateValue.DONE)) {
                                    statusLabel.setText("Connecting completed");
                                    progressBar.setValue(0);
                                }
                            }
                        }
                    });

            task.execute();
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        if (!saved) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Do you really want to disconnect? "
                    + "All unsaved data will be lost", "Accept", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                disconnect();
            }
        } else {
            disconnect();
        }
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void disconnect() {
        gc.close();
        gc = null;

        categoriesList.clearSelection();
        categoriesList.setListData(new Object[]{});

        connectionStateLabel.setText("<html><b>Not connected</b></html>");
        connectionStateLabel.setForeground(Color.RED);

        java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.NORTH;
        jPanel1.remove(connectedPanel);
        jPanel1.add(disconnectedPanel, gridBagConstraints);
        jPanel1.repaint();

        // Enabling menu items
        connectMenuItem.setEnabled(true);
        openFileMenuItem.setEnabled(false);
        saveFileMenuItem.setEnabled(false);
        saveFileAsMenuItem.setEnabled(false);
        disconnectMenuItem.setEnabled(false);
        addCategoryButton.setEnabled(false);

        statusLabel.setText("Disconnected");

        saved = true;
    }
    
    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        if (!saved) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Really open new file? "
                    + "All unsaved changes will be deleted", "Accept", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                openFile();
            }
        } else {
            openFile();
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void openFile() {
        GoogleFileChooserDialog fileChooser = new GoogleFileChooserDialog(this, true, service);
        fileChooser.setLocationRelativeTo(this);
        int result = fileChooser.showOpenDialog();

        if (result == GoogleFileChooserDialog.RESULT_OK) {
            File file = fileChooser.getSelectedFile();

            DownloadFileTask task = new DownloadFileTask(service, file);
            task.addPropertyChangeListener(
                    new PropertyChangeListener() {
                        public void propertyChange(PropertyChangeEvent evt) {
                            if ("state".equals(evt.getPropertyName())) {
                                Object value = evt.getNewValue();
                                if (value.equals(SwingWorker.StateValue.STARTED)) {
                                    statusLabel.setText("File download");
                                    progressBar.setValue(20);
                                }
                                if (value.equals(SwingWorker.StateValue.DONE)) {
                                    statusLabel.setText("File opened");
                                    progressBar.setValue(0);
                                }
                            }
                        }
                    });

            task.execute();

            for (ActionListener listener : openFileButton.getActionListeners()) {
                openFileButton.removeActionListener(listener);
            }

            openFileButton.setText("Save");
            openFileButton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    saveFileButtonActionPerformed(e);
                }
            });
        }
    }
    
    private void recordsTableValueChanged(javax.swing.event.ListSelectionEvent evt) {
        boolean selected = recordsTable.getSelectedRow() != -1;

        editRecordButton.setEnabled(selected);
        deleteRecordButton.setEnabled(selected);
    }

    private void categoriesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoriesListValueChanged
        boolean selected = !categoriesList.isSelectionEmpty();

        deleteCategoryButton.setEnabled(selected);

        searchTF.setEnabled(selected);
        addRecordButton.setEnabled(selected);
        editRecordButton.setEnabled(editRecordButton.isEnabled() && selected);
        deleteRecordButton.setEnabled(deleteRecordButton.isEnabled() && selected);

        if (selected) {
            OdfTableModel tableModel = new OdfTableModel();

            MediaType mediaType = manager.loadTableToMediaType(categoriesList.getSelectedValue().toString());
            tableModel.setMediaType(mediaType);
            recordsTable.setModel(tableModel);
         } else {
            recordsTable.setModel(new OdfTableModel());
         }

        this.searchText();

    }//GEN-LAST:event_categoriesListValueChanged

    private void addCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryButtonActionPerformed
        MediaType type = Dialogs.newMediaTypeDialog(manager.getMediaNames());

        if (type != null) {
            manager.addMediaType(type.getName(), type.getAttributes());
            DefaultListModel model = (DefaultListModel) categoriesList.getModel();

            model.addElement(type.getName());
            saved = false;
        }
    }//GEN-LAST:event_addCategoryButtonActionPerformed

    private void deleteCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategoryButtonActionPerformed
        manager.deleteMediaType(categoriesList.getSelectedValue().toString());
        DefaultListModel model = (DefaultListModel) categoriesList.getModel();
        int index = categoriesList.getSelectedIndex();
        model.remove(index);
        saved = false;
    }//GEN-LAST:event_deleteCategoryButtonActionPerformed

    private void addRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordButtonActionPerformed
        OdfTableModel model = (OdfTableModel) recordsTable.getModel();
        List record = Dialogs.newRecordDialog(model.getMediaType());

        if (record != null) {
            model.fireInserted();
            manager.addRecord(categoriesList.getSelectedValue().toString(), record);
            saved = false;
        }
    }//GEN-LAST:event_addRecordButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        if (this.actualFile.getId().isEmpty()) {
            // File is new, is not loaded
            saveAsFileButtonActionPerformed(evt);
        } else {
            SwingWorker task;

            // Content
            java.io.File content = manager.saveSpreadSheet();

            task = new SaveFileTask(service, actualFile, content);

            task.addPropertyChangeListener(
                    new PropertyChangeListener() {
                        public void propertyChange(PropertyChangeEvent evt) {
                            if ("state".equals(evt.getPropertyName())) {
                                Object value = evt.getNewValue();
                                if (value.equals(SwingWorker.StateValue.STARTED)) {
                                    statusLabel.setText("File saving");
                                    progressBar.setValue(20);
                                }
                                if (value.equals(SwingWorker.StateValue.DONE)) {
                                    statusLabel.setText("File saved");
                                    progressBar.setValue(0);
                                }
                            }
                        }
                    });

            task.execute();
        }
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void saveAsFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsFileButtonActionPerformed
        GoogleFileChooserDialog fileChooser = new GoogleFileChooserDialog(this, true, service);
        fileChooser.setLocationRelativeTo(this);
        int result = fileChooser.showSaveDialog();

        SwingWorker task;
        if (result == GoogleFileChooserDialog.RESULT_OK) {
            File file = fileChooser.getSelectedFile();

            if (service.isFolder(file)) {
                // Folder selected. Need to get name of the new file from the text field
                String name = fileChooser.getInsertedFileName();
                if (!name.endsWith(".ods")) {
                    name += ".ods";
                }

                File newFile = new File();
                newFile.setTitle(name);
                newFile.setDescription(actualFile.getDescription());
                newFile.setMimeType(actualFile.getMimeType());
                ParentReference parent = new ParentReference();
                parent.setId(file.getId());
                newFile.setParents(Collections.singletonList(parent));

                // Content
                java.io.File content = manager.saveSpreadSheet();

                task = new SaveNewFileTask(service, newFile, content);
            } else {
                // Content
                java.io.File content = manager.saveSpreadSheet();

                task = new SaveFileTask(service, file, content);
            }
            task.addPropertyChangeListener(
                    new PropertyChangeListener() {
                        public void propertyChange(PropertyChangeEvent evt) {
                            if ("state".equals(evt.getPropertyName())) {
                                Object value = evt.getNewValue();
                                if (value.equals(SwingWorker.StateValue.STARTED)) {
                                    statusLabel.setText("File saving");
                                    progressBar.setValue(20);
                                }
                                if (value.equals(SwingWorker.StateValue.DONE)) {
                                    statusLabel.setText("File saved");
                                    progressBar.setValue(0);
                                }
                            }
                        }
                    });

            task.execute();
        }
    }//GEN-LAST:event_saveAsFileButtonActionPerformed

    private void deleteRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordButtonActionPerformed
        OdfTableModel model = (OdfTableModel) recordsTable.getModel();
        manager.deleteRecord(categoriesList.getSelectedValue().toString(), recordsTable.getSelectedRow() + 1);
        model.getMediaType().getRecords().remove(recordsTable.getSelectedRow());

        model.fireDeleted(recordsTable.getSelectedRow());
        saved = false;
    }//GEN-LAST:event_deleteRecordButtonActionPerformed

    private void editRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRecordButtonActionPerformed
        OdfTableModel model = (OdfTableModel) recordsTable.getModel();
        List newAttributes = Dialogs.editRecordDialog(recordsTable.getSelectedRow(), model.getMediaType());
        manager.editRecord(categoriesList.getSelectedValue().toString(), recordsTable.getSelectedRow() + 1, newAttributes);

        model.fireUpdate(recordsTable.getSelectedRow());

        if (newAttributes != null) {
            manager.editRecord(categoriesList.getSelectedValue().toString(), recordsTable.getSelectedRow() + 1, newAttributes);
            model.fireUpdate(recordsTable.getSelectedRow());
        }
        saved = false;
    }//GEN-LAST:event_editRecordButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        if (!saved) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Do you really want to exit? "
                    + "All unsaved data will be lost", "Accept", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } else {
            disconnect();
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void disconnectedPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_disconnectedPanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_disconnectedPanelComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JButton addRecordButton;
    private javax.swing.JList categoriesList;
    private javax.swing.JButton connectButton;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JPanel connectedPanel;
    private javax.swing.JLabel connectionStateLabel;
    private javax.swing.JButton deleteCategoryButton;
    private javax.swing.JButton deleteRecordButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JPanel disconnectedPanel;
    private javax.swing.JButton editRecordButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton openFileButton;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel quickMenuBar;
    private javax.swing.JTable recordsTable;
    private javax.swing.JMenuItem saveFileAsMenuItem;
    private javax.swing.JMenuItem saveFileMenuItem;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTF;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * SwingWorker background task downloading file from Google Drive
     * 
     */
    private class DownloadFileTask extends SwingWorker<java.io.File, Integer> {

        private final File fileToDownload;
        private final GoogleDriveService service;

        public DownloadFileTask(GoogleDriveService service, File file) {
            this.service = service;
            this.fileToDownload = file;
        }

        @Override
        protected java.io.File doInBackground() throws Exception {
            return service.downloadFile(fileToDownload);
        }

        @Override
        protected void done() {
            statusLabel.setText("File downloaded");
            try {
                java.io.File downloadedFile = this.get();

                actualFile = fileToDownload;

                manager = new DomManagerImpl(downloadedFile);

                DefaultListModel model = new DefaultListModel();
                for (int i = 0; i < manager.getMediaNames().size(); i++) {
                    model.add(i, manager.getMediaNames().get(i));
                }
                categoriesList.setModel(model);

                saved = true;
                addCategoryButton.setEnabled(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "File open error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * SwingWorker background task saving updating file saved at Google Drive
     */
    private class SaveFileTask extends SwingWorker<File, Integer> {

        private final File fileToSave;
        private final java.io.File content;
        private final GoogleDriveService service;

        public SaveFileTask(GoogleDriveService service, File file, java.io.File content) {
            this.service = service;
            this.fileToSave = file;
            this.content = content;
        }

        @Override
        protected File doInBackground() throws Exception {
            return service.updateFile(fileToSave, content);
        }

        @Override
        protected void done() {
            try {
                File updatedFile = this.get();

                if (updatedFile == null) {
                    JOptionPane.showMessageDialog(rootPane, "File open error", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    actualFile = updatedFile;
                    statusLabel.setText("File saved");
                    saved = true;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "File open error", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ExecutionException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "File open error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * SwingWorker background task saving new file to Google Drive
     */
    private class SaveNewFileTask extends SwingWorker<File, Integer> {

        private final File fileToSave;
        private final java.io.File content;
        private final GoogleDriveService service;

        public SaveNewFileTask(GoogleDriveService service, File file, java.io.File content) {
            this.service = service;
            this.fileToSave = file;
            this.content = content;
        }

        @Override
        protected File doInBackground() throws Exception {
            return service.saveFile(fileToSave, content);
        }

        @Override
        protected void done() {
            try {
                File updatedFile = this.get();

                if (updatedFile == null) {
                    JOptionPane.showMessageDialog(rootPane, "File save error", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    actualFile = updatedFile;
                    statusLabel.setText("File saved");

                    saved = true;
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "File save error", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ExecutionException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "File save error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * SwingWorker background task connecting to Google Drive account.
     */
    private class ConnectToGoogleDriveTask extends SwingWorker<GoogleDriveService, Integer> {

        public static final int CONNECTION_SUCCESSFUL = 0;
        public static final int CONNECTION_FAILED = 1;
        private final GoogleConnection gc;
        private final String code;

        public ConnectToGoogleDriveTask(GoogleConnection gc, String code) {
            this.gc = gc;
            this.code = code;
        }

        @Override
        protected GoogleDriveService doInBackground() throws Exception {
            GoogleDriveService gds = null;
            try {
                gc.connect(code);
                if (gc.isConnected()) {
                    publish(CONNECTION_SUCCESSFUL);
                    gds = gc.buildService();
                } else {
                    publish(CONNECTION_FAILED);
                }

            } catch (Exception ex) {
                Logger.getLogger(MainView.class
                        .getName()).log(Level.INFO, null, ex);
            }
            return gds;
        }

        @Override
        protected void process(List<Integer> chunks) {
            for (int chunk : chunks) {
                if (chunk == CONNECTION_SUCCESSFUL) {
                    statusLabel.setText("Connected. Checking permissions");
                    progressBar.setValue(50);
                } else {
                    statusLabel.setText("Connection error");
                    progressBar.setValue(0);
                }
            }
        }

        @Override
        protected void done() {
            try {
                GoogleDriveService gds = this.get();

                if (gds != null) {
                    service = gds;

                    connectionStateLabel.setText("<html><b>You are connected</b></html>");
                    connectionStateLabel.setForeground(Color.GREEN);

                    for (ActionListener listener : openFileButton.getActionListeners()) {
                        openFileButton.removeActionListener(listener);
                    }

                    openFileButton.setText("Open");
                    openFileButton.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            openFileButtonActionPerformed(e);
                        }
                    });

                    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.gridx = 0;
                    gridBagConstraints.gridy = 2;
                    gridBagConstraints.fill = java.awt.GridBagConstraints.NORTH;
                    jPanel1.remove(disconnectedPanel);
                    jPanel1.add(connectedPanel, gridBagConstraints);
                    jPanel1.repaint();

                    // Enabling menu items
                    connectMenuItem.setEnabled(false);
                    openFileMenuItem.setEnabled(true);
                    saveFileMenuItem.setEnabled(true);
                    saveFileAsMenuItem.setEnabled(true);
                    disconnectMenuItem.setEnabled(true);
                    addCategoryButton.setEnabled(true);

                    saved = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Connection unsuccesfull", "Connection error", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(MainView.class
                        .getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,
                        "Connection unsuccesfull", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ExecutionException ex) {
                Logger.getLogger(MainView.class
                        .getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,
                        "Connection unsuccesfull", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public static Image getImage(final String pathAndFileName) {
        final URL url = Thread.currentThread().getContextClassLoader().getResource(pathAndFileName);
        return Toolkit.getDefaultToolkit().getImage(url);
    }
}